[tool.poetry]
name = "discord_bot"
version = "0.1.0"
description = ""
authors = ["1119-2916 <ti11192916@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
"discord.py" = "^2.3.2"
black = "^23.12.0"
openai = "^1.6.1"
tiktoken = "^0.5.2"
numpy = "^1.26.2"
urlextract = "^1.8.0"
requests = "^2.31.0"
bs4 = "^0.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
